### ISSUE TITLE
Determine claim precedents influence on outcome

### ISSUE THREAD

**Issue by dodoels** [Cyberjusticelab/JusticeAI#14]
*Description*
As a user, I would like to know which precedents had the most impact on the outcome

*Scope of Work*

*Acceptance Criteria*

*Story Points*
- 100

*Priority*
- High

*Risk*
- High

**Comment by arekmano** [comment]
Original Comment: "Hierarchy of norms. Check decisions that have been appealed. Check how many times decision has been cited."

**Comment by arekmano** [comment]
With regards to the original comment, in terms of Regie du logement, are the precedent's decisions still cited often? How does that assist us in determining which precedent had the most impact?

**Comment by naregeff** [comment]
Some decisions may have been appealed to the Court of Quebec or higher, in which case they will be referred to quite often. If a case is being cited often, it usually is an impactful case in that subset of law. 

Ex: there are almost no administrative law decisions that don't mention "Dunsmuir" and it's a relatively recent decision, therefore it is an important decision. [CanLII lists 13,000+ decisions that cite Dunsmuir since the decision was rendered in 2008.](https://www.canlii.org/en/#search/origin1=%2Fen%2Fca%2Fscc%2Fdoc%2F2008%2F2008scc9%2F2008scc9.html&nquery1=dunsmuir)

**Comment by arekmano** [comment]
Is there a similar dynamic in law that governs tenant/landlords?

**Comment by naregeff** [comment]
Do you mean "are there seminal decisions in landlord/tenant law"? If so, I don't know off the top of my head, but I can try to find out.
