### ISSUE TITLE
Determine probability of claim being awarded

### ISSUE THREAD

**Issue by dodoels** [Cyberjusticelab/JusticeAI#18]
*Description*
- As a user, I want the system to tell me whether the amount ($) a user claims is reasonable

*Scope of Work*

*Acceptance Criteria*

*Story Points*
- 3

*Priority*
- Medium

*Risk*
- High

**Comment by arekmano** [comment]
Original Comment: "Identify distribution curve. Compare amount proposed with distribution of amounts awarded. Check for extenuating circumstances."

**Comment by arekmano** [comment]
Distribution of amounts seems reasonable. Looking at distance from the mean, among common cases, we can return the probability of obtaining a given sum of money.

However, what is extenuating circumstance? Can we be provided with particular examples?

Additionally, this story depends on #16

**Comment by naregeff** [comment]
>However, what is extenuating circumstance? Can we be provided with particular examples?

One such example would be one of the parties acting in bad faith. Ex. landlord wants to evict because of a religious issue -> discrimination -> punitive damages.

**Comment by arekmano** [comment]
In this case, I think that this story may be split into these 3 stories:

As a user, I want the system to determine the amount of punitive damages that I should be awarded.
As a user, I want the system to determine whether or not my case involves a party that acted in bad faith (religious, gender, sexuality discrimination)
As a user, I want the system to extract whether or not a previous court case involved a party acting in bad faith

#79 #80 #81 

Additional stories can be added to consider other "extenuating" circumstances. Working on concrete circumstances should help develop the system incrementally, rather than attempting to consider all of them at once (i.e. shotgun approach)
