### ISSUE TITLE
Pause conversation

### ISSUE THREAD

**Issue by dodoels** [Cyberjusticelab/JusticeAI#23]
*Description*
- As a user, I would like to be able to save the progress on my claim

*Scope of Work*

*Acceptance Criteria*

*Story Points*
- 5

*Priority*
- Low

*Risk*
- Low

**Comment by arekmano** [comment]
Clarification is needed: What do we mean by pause the conversation? Does this mean start a conversation and continue it on another device? Or does it mean i leave my browser open for a while then come back? Or does it mean navigating away from the page and then navigating back?

**Comment by naregeff** [comment]
Verified. Means getting a code and being able to resume your session with said code (on same or other device, potentially after inactivity or navigating away).

**Comment by lancelafontaine** [comment]
I just wanted to bring up that in order to resume a session on another device, this implies that the user must create an account with us. To retrieve their information on another device, they'll need to login to their account. We could always prompt for the creation of an account at the end of the chat.

**Comment by arekmano** [comment]
2 possible uses of the code, which I do not think can apply in our case.

1: Use the code to resume conversation at a specific point. The site that you showed us (from British-Columbia, which I can't find now) used this technique. They were able to use this technique since their interaction was limited to choosing from a few options that were given to them. Essentially, each possible scenario was given a code, which any user could use to return to that point, Within our system we cannot apply this "code" method, since the user will potentially do more than selecting from various options (namely uploading their lease + receipts), and accessing documents related to their claim (#22, #49). 

2: Use code as a method of authentication. Essentially, we would generate a unique token for each individual as they progress with their conversation. What this means is that anyone with that token can essentially impersonate you within our system, and may also have access to files that you previously uploaded. This isn't a good approach.

A better option would be to use an account-based solution, as detailed in #30

**Comment by arekmano** [comment]
Since we are sticking to user accounts (see conversation #30), is this user story required?

**Comment by dodoels** [comment]
I believe this is duplicates/part of #30

**Comment by arekmano** [comment]
Closing as the functionality is included in #30
