### ISSUE TITLE
Redesign beta page 2.0

### ISSUE THREAD

**Issue by arekmano** [Cyberjusticelab/JusticeAI#264]
*Description*
As a user, I would like the beta sign up to have user responses defined in Zeus' question

*Scope of Work*
- [ ] Create high-fid mockup
- [ ] Implement UI tweaks

**Comment by arekmano** [comment]
tentative UI redesign:

![image](https://user-images.githubusercontent.com/8740734/34910736-a4a24184-f889-11e7-9e6a-826b262f0b38.png)

![image](https://user-images.githubusercontent.com/8740734/34910794-5f456714-f88a-11e7-9894-5a9745af3c00.png)

![image](https://user-images.githubusercontent.com/8740734/34910810-b23b4a74-f88a-11e7-8e59-1b1b92fd9c97.png)


Question's answers are in the chat bubble itself

**Comment by arekmano** [comment]
PO input needed @naregeff

**Comment by naregeff** [comment]
yeah, this is definitely better than having the interactions at the bottom. PO approves this method!

I provided a tentative workflow + strings to be used, in Slack. 

The main difference is at step 1:

- Current workflow asks if user has a question, then provides opportunity to ask question if user answers yes.
- Proposed workflow asks user to input question or indicate they have no questions. 

Advantage = one less interaction to get to same result.

**Comment by arekmano** [comment]
The proposed workflow change requires a bit of rework. Creating a new ticket

**Comment by dodoels** [comment]
I recommend saving both methods. @arekmano I see you already implemented this method in latest PR, but for mobile users this can be a less good UX. Mobile users prefer having standard chat on their screen instead of following the input inside the bubbles. Also, you might want to test out if the virtual keyboard on your mobile screen doesn't overlay on the input text box -> user won't be able to see what they type.

**Comment by dodoels** [comment]
My suggestion is to switch between two methods based on device type.

**Comment by arekmano** [comment]
closed since it is the same as #272
