### ISSUE TITLE
Legal Definitions

### ISSUE THREAD

**Issue by naregeff** [Cyberjusticelab/JusticeAI#37]
*Description*
- As a layman, I want the chatbot to  provide legal definitions anytime it uses a legal term

The chatbot may from time to time use terms that are beyond the understanding of a regular citizen. It is important that these terms have definitions that can be gleaned by mousing over, or even by asking the bot what it means.

*Scope of Work*
- Add a dictionary of all possible legal terms to the system
- Add a tooltip hover for complex legal terms
- Add complex word outlining on the back-end

*Acceptance Criteria*
- Given a simple interaction, with the system asking the question: "Are you a tenant or a landlord?", both "tenant" and "landlord" words should clearly be outlined as hover-able. Upon mouse hover, their definitions should be shown to the user.

**Comment by naregeff** [comment]
Verified, Priority medium.

**Comment by arekmano** [comment]
**Attached are all the responses that the chatbot currently says:**


No. There is no allowable delay after signing a lease.

There are many recourses available to the tenant: rent reduction; rent deposit; authorization of the Régie to do himself the repairs; resiliation of the lease; Damages; order to force the landlord to make the repairs. A decision must be rendered by the Régie du logement allowing one of these recourses to be applied.

If you are suffering harassment, find someone to possibly serve as a witness testimony and document the events with the aid of an audio-visual device (ie: cell phone).

You should file an immediate demand letter to your landlord demanding for the harassment to cease and a possible lease resiliation or compensation for moral damages.

If your landlord is not receptive, you may file at the Régie du logement for a hearing. The Commission des droits de la personne et des droits de la jeunesse can also give you aid.

Be aware that if you leave your dwelling, you still need to pay unless the regie or the landlord allows you to resiliate your lease.

If your landlord fails to answer the phone or does not offer help in an emergency, call a professional immediately.

If your landlord refuses to refund you for the emergency service you paid for, write a demand letter informing the landlord that you need to be compensated and file for a hearing at the Regie du logement if you are not reimbursed.

If authorities, the insurance company or the Regie du logement find that the damage to the apartment was caused by your neglect, you may face financial repercussions. If not, any financial loss during the emergency will be compensated for including temporary accommodations.

If you are being abused by a spouse or a loved one, vacate the dwelling immediately and stay with friends, relatives, or contact a local shelter. File a police report immediately.

Acquire the form for requesting an attestation for lease resiliation due to spousal violence and fill it out.

Bring the form to a commissioner of oaths and get it signed.

Submit the form to your local courthouse.

Once you receive your attestation, you may send it with a registered letter to your landlord indicating the nature of your resiliation. Keep in mind that you must legally continue to pay rent for the dwelling until the lease is fully terminated.

To transfer a lease, find a new tenant and complete the Notice to Assign the Lease form.

Send this form along with a completed credit check via registered mail to your landlord.

Your landlord has 15 days to respond, and is only technically allowed to refuse for a good reason, such as the belief that the new tenant will not be able to pay rent. If the landlord does not respond in 15 days, the lease transfer is automatically approved.

Sign the Assignment of the Least Agreement form with the new tenant that includes any conditions in transferring your lease.

If the transfer goes through, leave your copy of the original lease with the new tenant, and you’re free to move out!

A subtenant is someone that lives in your dwelling temporarily and pays rent for the time you are gone. However, bear in mind that you are ultimately responsible for the rent and condition of the dwelling.

Once you’ve found a subtenant, pick up an official Quebec lease and cross out the words “tenant” and “landlord” in the identification box and replace them with “sub-tenant” and “tenant”.

Fill out a Notice to Sublet form and send it to your landlord. Your landlord has 15 days to respond.

Finally, figure out a way to make rent payments with your subtenant. For example, transferring you money on a regular basis to pay the rent, or having a roommate make sure the rent gets paid.

If your dwelling becomes uninhabitable, you must first call the city inspectors to obtain an official report that deems your dwelling as unfit for habitation before abandoning it.

If your dwelling is deemed as unfit for habitation, send the notice of abandonement form by registered mail to your landlord prior to or after abandoning the dwelling.

Bear in mind that if you are responsible for making the dwelling unfit for habitation, such as starting a fire, you must keep paying rent until your lease is resiliated.

If the reason for abandonment was out of your control, you may have the right to cease paying rent.

To find your landlord’s contact information, visit Consultation du rôle d'évaluation foncière.

Enter the address of your dwelling. If the dwelling is found, your landlord and their contact information will be available.

Most of the time, informal communication with your landlord is enough to solve most problems. However, if your landlord doesn’t address the problem, you must send a demand letter.

A demand letter must be sent via registered mail. You may request this service at a post office as it requires a signature from the recipient upon delivery.

Begin the letter with the phrase “Without Prejudice” as this letter is intended as a formal notice of discontent. Bear in mind that this letter can be used as evidence in court, so refrain for foul language or personal attacks.

In your letter, include in chronological order the events, people, or places that are implicated in your demand. Provide details such as emails, phone calls, or text messages exchanged between you and the opposing party.

Once you’ve outlined your situation, make demands in point form so that the other party knows clearly what you want. Provide a time limit in which the other party must act.

Finally, inform the other party of the possible legal recourse you will take, such as taking your landlord to the Régie du Logement or taking a roommate to Civil Court, or contacting city inspectors.

Housing committees help walk you through your housing rights and responsibilities.

Consult this list to find one near you

For any matter that involves legal information, you will need to visit the housing committee in person.

You must obtain a postponement of the hearing by obtaining a written consent of the other party and by filing it at la Régie.

If you cannot obtain that consent, you can either send a mandatary who will ask for the postponement or write to la Régie du logement and ask for the postponement of the case.

The reasons for the asked postponement must be indicated and a copy sent to the other party.

You must obtain a postponement of the hearing by obtaining a written consent of the other party and by filing it at la Régie.

If you cannot obtain that consent, you can either send a mandatary who will ask for the postponement or write to la Régie du logement and ask for the postponement of the case.

The reasons for the asked postponement must be indicated and a copy sent to the other party.

The landlord may attempt to minimize the damages by trying to rent the dwelling to another person.

They may claim from the tenant who has abandoned the premises a relocation indemnity to recover the lost rent.

The landlord has three years to file the application at the Régie du logement.

You should minimize the damages of abandonment by trying to rent the dwelling to another person.

You may claim from the tenant who has abandoned the premises a relocation indemnity to recover the lost rent.

 You have three years to file the application at the Régie du logement.

Your landlord cannot do so without the authorization of the Régie du logement except in the case of a necessary and urgent repair and also in that case that you are unable to reach the landlord in order to inform him about the situation.

Your tenant cannot do so without the authorization of the Régie du logement except in the case of a necessary and urgent repair and also in that case where your tenant is not able to reach you in order to inform you about the situation.

Whatever the time of day, according to reasonable circumstances, another tenant (or you) cannot make excessive noise.

However, if the source of the noise is produced by a tenant or a party that is not on your landlord’s jurisdiction, it is out of their hands.

Whatever the time of day, according to reasonable circumstances, a tenant cannot make excessive noise.

However, if the source of the noise is produced by a tenant or a party that is not on your property, it is out of your hands.

The landlord must pay for the repairs except if they can successfully establish that you are responsible for the damages.

If you are able to prove that you are not responsible for the damages, and if the repair is urgent (i.e. no running water), you may take the matter into your own hands and have the right to be reimbursed.

You may also plead your case in front of la Régie if you were not compensated for your work.

You must pay for the repairs except if you can successfully prove that your tenant is responsible for the damages.

If the tenant is able to prove that they are not responsible for the damages, and if the repair is urgent (i.e. no running water), the tenant may take the matter into their own hands.

Your tenant has the right to be reimbursed and plead in front of la Régie if they were not reasonably financially compensated by you.

Your landlord must give you a 24 hour notice prior to entering your dwelling.

They must make the visit between 9:00 AM and 9:00 PM.

You must give your tenant a 24 hour notice prior to entering their dwelling.

You must make the visit between 9:00 AM and 9:00 PM.

There is no specified date for heating the dwelling.

The landlord must start to heat the dwellings of the building as soon as the climatic conditions justify it.

Although neither law or most municipal by-law are specific in this area, the temperature of the dwelling should be around 21C.

There is no specified date for heating the dwelling.

You must start to heat the dwellings of the building as soon as the climatic conditions justify it.

Although neither law or most municipal by-law are specific in this area, the temperature of the dwelling should be around 21C.

There is no fixed rate increase applied by the Régie du logement. Each case is treated specifically.

The Régie takes into account, in calculating the rent variation, the income of the building and the municipal and school taxes, the insurance bills, the energy costs, maintenance and service costs.

Also, it sees to apply a return on capital expenditures, if there were such expenditures, and indexes the net income of the building.

In order to give an estimate of the rent variation for a dwelling, see this.

There is no set-in-stone way of calculating a rent increase and each case is treated differently.

When calculating the increase, la Régie takes into account the income of the building, the municipal and school taxes, the insurance bills, the energy costs, maintenance and service costs.

Also, it sees to apply a return on capital expenditures such as maintenance or infrastructure upgrades.

In order to get an estimate of the rent increase of a lease, see this.

Any key deposits, rent advances, damage deposits, security deposits, etc. are illegal and you are not obliged to pay any of them.

Consider all other requested fees (laundry machine access, pools, kitchen appliances), if already granted in your lease, as illegal too.

Lease transfer fees and sublet fees are also illegal.

However, according to the Civil Code of Quebec (article 1904), your landlord may ask for the first month’s rent to be paid in advance right after the signature of the lease.

Good news though! Even if you signed a document saying you’d pay for any of these fees, they are without effect! You cannot sign away your rights.

Any key deposits, rent advances, damage deposits, security deposits, etc. are illegal and tenants are not obliged to pay any of them.

Consider all other requested fees (laundry machine access, pools, kitchen appliances), if already granted in their lease, as illegal too.

Lease transfer fees and sublet fees are also illegal.

However, according to the Civil Code of Quebec (article 1904), you may ask for their first month’s rent to be paid in advance right after the signature of the lease.

 Even if the tenant signed a document saying they’d pay for any of these fees, they are without effect! They cannot sign away their rights.

Your landlord is not legally allowed to collect personal information such as copies of your study permit, driver’s license, passports, health cards, bank account numbers or even your social insurance number (SIN).

If you’ve given this kind of sensitive information to your landlord, you can:

1. Demand a copy of every piece of sensitive information in a written demand letter sent by registered mail.

2. Demand in a second letter the destruction of said information.

If the landlord doesn’t abide in full to your demand, file a claim with the Commission d'accès à l’information du Québec (CAIQ).

 Even if you signed a clause saying you’ll willingly give this information away, you cannot sign away your rights, making that clause legally invalid.

Careful, as a landlord you are not legally allowed to collect personal information such as copies of your tenant’s study permit, driver licenses, passports, health cards, bank account numbers or even their social insurance number (SIN).

Your tenant is legally allowed to file a claim with the Commission d'accès à l’information du Québec (CAIQ) if you request such information.

Even if the tenant signed a clause saying they willingly gave this information away, they cannot sign away their rights, making that clause legally invalid.

The RL-31 allows you to claim your housing as part of the solidarity tax credit.

You are eligible to receive the RL-31 if you are a tenant or a subtenant.

Your landlord is responsible for providing you with the RL-31 prior to the last day of February.

If your landlord has not provided you with your RL-31, contact them and ask them to provide one as it is required by law.

If they refuse to do so, call Revenu Québec and they will accept a copy of your lease.

The RL-31 allows your tenant to claim the provided housing as part of the solidarity tax credit.

Tenants and subtenants are equally eligible to receive it.

You are responsible by law for providing them with the RL-31 prior to the last day of February.

If you are sure that you were not negligent and damage was caused due to wear and tear

write your landlord a demand letter stating that something is broken and needs fixing.

If you are sure that the tenant was negligent and damage was not caused due to wear and tear

present your arguments in front of la Régie du logement if the tenant refuses to pay for the damages.

The easiest way to obtain a credit check is to go online.

Find a reputable credit score provider online (which typically costs you a small fee) and provide them with your SIN.

 Your credit report will then immediately be available to print out and submit to your landlord.

The responsibility of providing a credit report is your tenant’s.

The easiest way to obtain a credit check for your tenant is for them to get it online.

They need to find a reputable credit score provider online (which typically costs them a small fee) and provide them with their SIN.

Their credit report will then immediately be available to print out and submit to you.

Sorry, I'm unable to help you with that at the moment.

Would you deem the apartment unfit for habitation?

Is your apartment infested with any sort of pest?

Have you received any complaints of the tenant acting in a disruptive manner?

Has the tenant failed to abide by a previous Regie judgement?

Have you at any point hired an inspector to track down the fleeing tenant?

Did you notify your tenant in advance about your intentions to retake the apartment?

Have moving expenses been compensated when the apartment was deemed inhabitable?

Has there been an attempt to change the rent during the term of the lease?

Are there any supporting documents justifying an increase in rent?

Is the apartment being taken back to lodge the landlord or their family member?

Have moving expenses been compensated when the apartment was to be retaken by the landlord?

Has an inquiry been made with the Regie du logement?

Has a debt acknowledgment been signed by the tenant?

Has proof of ability to pay for the rented property been provided?

Has the rent been increased during the term of the lease?

Has the tenant continually been late with their rent payments?

Was there any damage done to the rented property?

Is the tenant dead?

Is the apartment dirty?

If there are multiple tenants inside of the apartment, do they all share the same lease?

If there are multiple tenants inside of the apartment, does each possess their own lease?

Was there a mutually beneficial agreement set by both parties?

Is there a specified end date to the lease?

Has the tenant left the apartment?

Is there a monthly rent payment?

Has the tenant displayed any negligence with the rental?

Has a request for cancellation of the lease been given by any of the parties?

Has the tenant refused the takeover of the apartment?

Has the tenant not paid rent for over 3 weeks?

Has the tenant demonstrated violent behavior?

Is the tenant withholding rent without having received permission from the Regie du logement?

Has the tenant’s payment habits caused you any prejudice?

Has your tenant been continuously late on their rent payments?

Did the tenant declare they are in a financially indisposed situation due to external factors? (i.e. job loss, injury, death in the family, etc.)

Does the tenant currently owe any rent?

If so, how much do they owe?

Has it been less than 3 weeks since the tenant has paid the landlord?

Was the remaining balance for rent paid before the hearing?

Oops, something went wrong finding a response. Sorry about that.

**Comment by arekmano** [comment]
How should we proceed defining the legal terms? @naregeff

**Comment by arekmano** [comment]
Running these sentences through the Oxford 3000 list (3000 most common words) we obtain outliers. Combining these with the Academic word list (list of words you are likely to run into at a university level), we obtain the following words:

>abandoned
abandoning
abandonment
abide
access
accommodations
acknowledgment
acquire
aid
allowable
appliances
area
assign
assignment
attestation
audio-visual
authorities
authorization
available
aware
beneficial
by-law
caiq
cancellation
cease
chronological
circumstances
civil
clause
climatic
code
commission
commissioner
communication
compensated
compensation
consent
consult
consultation
contact
contacting
continually
courthouse
credit
deem
deemed
deems
demonstrated
device
discontent
displayed
disruptive
document
documents
doesn’t
driver
dwelling
eligible
emails
energy
establish
estimate
evidence
excessive
expenditures
external
factors
fee
file
filing
finally
financial
financially
fleeing
foncière
found
granted
habitation
harassment
identification
illegal
implicated
income
indemnity
indicated
indicating
indisposed
infested
infrastructure
inhabitable
injury
inspector
invalid
involves
jeunesse
job
jurisdiction
justify
justifying
legal
license
lodge
logement
l’information
maintenance
mandatary
minimize
municipal
mutually
negligence
negligent
notify
oaths
obliged
obtain
obtaining
personne
pest
plead
postponement
prejudice
previous
prior
professional
receptive
recipient
recourse
recourses
recover
refrain
refund
regie
registered
reimbursed
relocation
rendered
rental
repercussions
reputable
require
resiliate
resiliated
resiliation
respond
response
retake
retaken
revenu
roommate
security
sin
solidarity
source
specific
specifically
specified
spousal
spouse
sub-tenant
sublet
submit
subtenant
technically
temporary
terminated
testimony
text
they’d
transfer
unfit
uninhabitable
upgrades
vacate
variation
via
withholding

**Comment by Vynny** [comment]
Prior to doing this we should revise a lot of the bot responses.

**Comment by naregeff** [comment]
The UI works, texts will be improved by stakeholder. 👍
