### ISSUE TITLE
Persist conversation text

### ISSUE THREAD

**Issue by lancelafontaine** [Cyberjusticelab/JusticeAI#66]
*Description*
As a user, I would like my conservations to be persisted.

*Scope of Work*
- [ ] Expose port in production
- [ ] Have production environment
- [ ] Figure out how to conveniently access prod data

*Story Points*
- 5

*Priority*
- High

*Risk*
- Low

*Demo requirement*
1. User chats with the bot
2. User can see the history of this conversation (in a database)

*Acceptance Criteria*
- User enters piece of conversation which is found in database
- Conversation can be retrieved for future analysis 

**Documentation, files, diagrams, etc. relating to this feature:**
Url, books, etc.

***Changes***:
- [Optional]

**Comment by lancelafontaine** [comment]
Blocked: needs a privacy policy / EULA. Issue: #5

**Comment by ghost** [comment]
Blocked: Somewhat confused between distinction between this issue and #23

**Comment by naregeff** [comment]
Unverified, don't follow the use of this user story. Please explain.

Edit: verified.
Edit2: priority high

**Comment by arekmano** [comment]
In order to perform a prediction about the user's claim, the system requires information gained from the user. This information needs to be persisted within our system at the very least temporarily (even if it is removed after a set time) for us to make a prediction.

This will also allow for the improvement to our chatbot's classifiers

**Comment by arekmano** [comment]
priority? From an architectural point of view, this is fairly critical for development to continue on the system.

**Comment by naregeff** [comment]
Does what it says it should do. Good work!
